name: Kernel Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Checkout zipper
      uses: actions/checkout@v3
      with:
        repository: Mocaness/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: yamaizano/android-kernel-actions@master
      id: build
      with:
        arch: arm64
        compiler: proton-clang/master
        defconfig: vendor/whyred-perf_defconfig
        image: Image.gz-dtb

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Kernel
        path: zipper
